name: Setup Node and pnpm
description: Setup Node.js, install pnpm, and install dependencies

runs:
    using: composite
    steps:
        - name: Setup Node
          uses: actions/setup-node@v4

        - name: Install pnpm
          shell: bash
          run: |
              npm install -g pnpm
              pnpm --version

        - name: Install dependencies
          shell: bash
          run: |
              pnpm install --frozen-lockfile
