name: Setup Node and pnpm
description: Setup Node.js, install pnpm, and install dependencies
inputs:
  node-version:
    description: Node.js version
    required: false
    default: "24.10"
  pnpm-version:
    description: pnpm version to install
    required: false
    default: "10.20"
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      shell: bash
      run: |
        npm install -g pnpm@${{ inputs.pnpm-version }}
        pnpm --version

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile
