services:
  dev:
    build:
      context: .
      dockerfile: ./docker/images/dev.dockerfile
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./apps:/app/apps
      - ./packages:/app/packages
      - ./assets:/app/assets
      - ./eslint-config.js:/app/eslint-config.js
    networks:
      backtrade:
        ipv4_address: 192.168.250.1

  postgres:
    build:
      context: .
      dockerfile: ./docker/images/postgres.dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backtrade:
        ipv4_address: 192.168.250.2
  

  redis:
    build:
      context: .
      dockerfile: ./docker/images/redis.dockerfile
    ports:
      - "6379:6379"
    networks:
      backtrade:
        ipv4_address: 192.168.250.3

volumes:
  postgres_data:
    driver: local

networks:
  backtrade:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.250.0/24
          gateway: 192.168.250.254
