services:
  cloudflared:
    build:
      context: .
      dockerfile: docker/images/cloudflared.prod.dockerfile
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run
    networks:
      backtrade:
        ipv4_address: 192.168.250.253
    restart: always

  proxy:
    build:
      context: .
      dockerfile: docker/images/proxy.prod.dockerfile
    ports:
      - "80:80" # Only for testing purposes. Remove this on real production, no port opening, only cloudflare tunnel
    networks:
      backtrade:
        ipv4_address: 192.168.250.1
    restart: always

  backend:
    build:
      context: .
      dockerfile: docker/images/backend.prod.dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      API_LOG_LEVEL: ${API_LOG_LEVEL}
      API_LOG_DIR: ${API_LOG_DIR}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      backtrade:
        ipv4_address: 192.168.250.2
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/images/frontend.prod.dockerfile
    networks:
      backtrade:
        ipv4_address: 192.168.250.3
    restart: always

  postgres:
    build:
      context: .
      dockerfile: docker/images/postgres.dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - backtrade_db:/var/lib/postgresql/data
    networks:
      backtrade:
        ipv4_address: 192.168.250.4
    restart: always

  redis:
    build:
      context: .
      dockerfile: docker/images/redis.dockerfile
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      backtrade:
        ipv4_address: 192.168.250.5
    restart: always

volumes:
  backtrade_db:
    driver: local

networks:
  backtrade:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.250.0/24
          gateway: 192.168.250.254
