name: Coverage
description: Run tests with coverage across the monorepo using pnpm and Vitest
inputs:
    working-directory:
        description: Directory to run the command in
        required: false
        default: "."
runs:
    using: composite
    steps:
        - name: Test with coverage
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: pnpm test:coverage
